# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

go1/himloco:
# him1119_2200 kp: 20
  model_name: "him1119_2200.pt"
  num_observations: 45
  observations: ["commands", "ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations_history: [0, 1, 2, 3, 4, 5]  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
#   rl_kp: [40, 40, 40,
#           40, 40, 40,
#           40, 40, 40,
#           40, 40, 40]
#   rl_kd: [1, 1, 1,
#           1, 1, 1,
#           1, 1, 1,
#           1, 1, 1]
  rl_kp: [20, 20, 20,
          20, 20, 20,
          20, 20, 20,
          20, 20, 20]
  rl_kd: [0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5]
#   rl_kp: [30, 30, 30,
#           30, 30, 30,
#           30, 30, 30,
#           30, 30, 30]
#   rl_kd: [0.8, 0.8, 0.8,
#           0.8, 0.8, 0.8,
#           0.8, 0.8, 0.8,
#           0.8, 0.8, 0.8]
  fixed_kp: [40.0, 40.0, 40.0,
             40.0, 40.0, 40.0,
             40.0, 40.0, 40.0,
             40.0, 40.0, 40.0]
  fixed_kd: [1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0]
  num_of_dofs: 12
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
  default_dof_pos: [ 0.1000, 0.8000, -1.5000,
                    -0.1000, 0.8000, -1.5000,
                     0.1000, 1.0000, -1.5000,
                    -0.1000, 1.0000, -1.5000]
  joint_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]
